---
jobs:
- name: job-hello-world
  public: true
  serial: true
  plan:
  - get: concourse_test
  - get: my-timer
    trigger: true
  - task: hello-world
    file: concourse_test/ci/task/task_hello_world.yml

resources:
- name: resource-tutorial
  type: git
  source:
    uri: https://github.com/buggavep/concourse_test.git

- name: my-timer
  type: time
  source:
    interval: 2m
