jobs:
  - name: hello_world_job
    plan:
    - task: hello_world_task
      config: 
        platform: linux
        image_resource:
          type_resource:
           type: docker-image
           source: { repositroy: ubuntu }
        run:
         path: echo
         args:
         - "Hello World"
