---
jobs:
- name: job-hello-world
  public: true
  serial: true
  plan:
  - get: resource-tutorial
#  - get: my-timer
    trigger: true
  - task: hello-world
    file: resource-tutorial/ci/task/task_hello_world.yml

resources:
- name: resource-tutorial
  type: git
  source:
    uri: https://github.com/buggavep/concourse_test.git

#- name: my-timer
#  type: time
#  source:
#    interval: 2m
